### ISSUE TITLE
Error: httpTransactionElement.parents.find is not a function 

### ISSUE THREAD

**Issue by runk** [apiaryio/dredd#882]
#### Describe your problem

After upgrade from v4.3 to v4.5 I started having the error:

```
error: httpTransactionElement.parents.find is not a function
info: Backend server process exited
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/runk/.nvm/versions/node/v7.6.0/bin/node',
1 verbose cli   '/Users/runk/.nvm/versions/node/v7.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dredd' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 verbose run-script [ 'predredd', 'dredd', 'postdredd' ]
5 info lifecycle @org/project@8.13.0~predredd: @org/project@8.13.0
6 silly lifecycle @org/project@8.13.0~predredd: no script for predredd, continuing
7 info lifecycle @org/project@8.13.0~dredd: @org/project@8.13.0
8 verbose lifecycle @org/project@8.13.0~dredd: unsafe-perm in lifecycle true
9 verbose lifecycle @org/project@8.13.0~dredd: PATH: /Users/runk/.nvm/versions/node/v7.6.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/runk/projects/project/node_modules/.bin:/Users/runk/.rvm/gems/ruby-2.3.1/bin:/Users/runk/.rvm/gems/ruby-2.3.1@global/bin:/Users/runk/.rvm/rubies/ruby-2.3.1/bin:/Users/runk/.nvm/versions/node/v7.6.0/bin:~/bin:/opt/local/bin:/opt/local/sbin:/opt/local/lib/postgresql91/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/runk/.rvm/bin
10 verbose lifecycle @org/project@8.13.0~dredd: CWD: /Users/runk/projects/project
11 silly lifecycle @org/project@8.13.0~dredd: Args: [ '-c', 'scripts/dredd' ]
12 silly lifecycle @org/project@8.13.0~dredd: Returned: code: 1  signal: null
13 info lifecycle @org/project@8.13.0~dredd: Failed to exec dredd script
14 verbose stack Error: @org/project@8.13.0 dredd: `scripts/dredd`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/runk/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/runk/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @org/project@8.13.0
16 verbose cwd /Users/runk/projects/project
17 error Darwin 16.7.0
18 error argv "/Users/runk/.nvm/versions/node/v7.6.0/bin/node" "/Users/runk/.nvm/versions/node/v7.6.0/bin/npm" "run" "dredd"
19 error node v7.6.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error @org/project@8.13.0 dredd: `scripts/dredd`
22 error Exit status 1
23 error Failed at the @org/project@8.13.0 dredd script 'scripts/dredd'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @org/project package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     scripts/dredd
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs @org/project
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls @org/project
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### What command line options do you use?

```
$ dredd --config docs/dredd.yml
```

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: lib/**/*.hook.js
language: nodejs
sandbox: false
server: npm start
server-wait: 7
init: false
custom: {}
# Set to `true` if you want to see test names
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: docs/index.apib
# Port 40001 is configured in ./scripts/dredd file
endpoint: 'http://localhost:40001'

```

#### What's your `dredd --version` output?

```
v4.5.0
```

#### Does `dredd --level=debug` uncover something?

Nope.

#### Can you send us failing test in a Pull Request?

No.

**Comment by michalholasek** [comment]
Hello @runk,

It seems to me you have `minim@0.19.1` installed for some reason. Could you please try remove all the packages (`rm -rf node_modules`) and install them from ground up (`npm install`)?

**Comment by honzajavorek** [comment]
@runk Did you manage to overcome the issue or is it still relevant?
