### ISSUE TITLE
Dredd cannot be installed directly from repository

### ISSUE THREAD

**Issue by nurey** [apiaryio/dredd#475]
I'm getting the following when running `dredd` after upgrading node to 6.1.0 and installing dredd via `npm install -g apiaryio/dredd`

module.js:440
    throw err;
    ^

Error: Cannot find module '../lib/dredd-command'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dredd/bin/dredd:6:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
➜  npm -v
3.8.6
➜  node -v
v6.1.0

**Comment by honzajavorek** [comment]
I don't know why exactly, but it seems that it's because you're installing by `npm install -g apiaryio/dredd` instead of `npm install -g dredd`. Why did you use the command you posted? Did you find it somewhere in documentation?

According to [npm docs](https://docs.npmjs.com/cli/install), your syntax will be resolved as npm installing from GitHub repository. Dredd is a library compiled from CoffeeScript and with all sorts of native dependencies. I'm not sure how much friendly installation directly from repository is.

**Comment by nurey** [comment]
I was trying the github variant of npm install because the standard install had failed for me. Now it's working. I guess you uploaded the latest version to npmjs?

**Comment by honzajavorek** [comment]
Yes, I had some problems to publish new npm package, so it was out of sync
with master and tags here for a while. I figured out it was due my network
and now the latest version is correctly published.

**Comment by smizell** [comment]
@nurey I'm only closing because it looks like your issue is resolved, but please feel free to open it back up if you are still having issues. Definitely want to help resolve anything you come across!
